safe: false # A hack as environment variable (https://github.com/plusjade/jekyll-bootstrap/issues/84)
auto: true
server: true
permalink: none
pygments: true

navigation:
  - text: overview
    url: /index.html
  - text: installation
    url: /installation.html
  - text: docs
    url: /documentation.html
  - text: contribute
    url: /contribute.html
